
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxcjkpnhlcrwaxarlxyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Y2prcG5obGNyd2F4YXJseHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzQ5MzAsImV4cCI6MjA1ODQxMDkzMH0.39MmELjeIwCaDjNIs-O2xQk1BmzAKAaB5bsRx9CVTY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize the data_sources table if it doesn't exist
export async function initializeDataSourcesTable() {
  const { error } = await supabase.rpc('initialize_data_sources_table');
  
  if (error) {
    console.error("Error initializing data_sources table:", error);
    
    // If the function doesn't exist, create the table directly
    if (error.code === 'PGRST301') {
      console.log("Creating data_sources table directly...");
      
      // Create the table using raw SQL
      const { error: sqlError } = await supabase.rpc('create_data_sources_table');
      
      if (sqlError) {
        console.error("Failed to create data_sources table:", sqlError);
      } else {
        console.log("Data sources table created successfully");
      }
    }
  } else {
    console.log("Data sources table initialized successfully");
  }
}

// Call the initialization function
initializeDataSourcesTable();
