// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxcjkpnhlcrwaxarlxyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Y2prcG5obGNyd2F4YXJseHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzQ5MzAsImV4cCI6MjA1ODQxMDkzMH0.39MmELjeIwCaDjNIs-O2xQk1BmzAKAaB5bsRx9CVTY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);